clone_folder: c:\projects\cg
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64

matrix:
  fast_finish: true

init:
- if "%platform%"=="x64" (set generator="Visual Studio 15 2017 Win64")
- if "%platform%"=="x64" (set arch=x64)
- echo %platform%
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- echo %generator%

cache: c:\tools\vcpkg\installed

before_build:
- vcpkg install assimp:%arch%-windows catch2:%arch%-windows glm:%arch%-windows qt5-base:%arch%-windows
- mkdir build
- cd build
- cmake --version
- cmake .. -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G %generator%

build:
  project: c:\projects\cg\build\Raytrace.sln
  verbosity: minimal
  parallel: true

test_script:
- cd c:\projects\cg\build
- ctest -C %configuration%