language: c++
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      compiler: clang

    - os: linux
      compiler: gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test